<?php
$host = "localhost";
$port = 3306;
$db   = "roiwi_ex3";
$user = "roiwi_roiwi";
$pass = "roiwi_roiwi";

$conn = new mysqli($host, $user, $pass, $db, $port);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
$conn->set_charset("utf8mb4");

function die_bad($msg) {
    http_response_code(400);
    die($msg);
}

function regenerate_shifts_js($conn) {
    $sql = "SELECT id, k_name, city, address, shift_date, start_time, end_time,
                   wage, kids, ages, phone, urgent, shift_type, notes, created_at
            FROM shifts
            ORDER BY created_at DESC";

    $res = $conn->query($sql);
    if (!$res) die("Select failed: " . $conn->error);

    $rows = [];
    while ($r = $res->fetch_assoc()) {
        $rows[] = [
            "id" => (int)$r["id"],
            "title" => $r["k_name"],
            "k_name" => $r["k_name"],

            "city" => $r["city"],
            "address" => $r["address"],

            "date" => $r["shift_date"],
            "shift_date" => $r["shift_date"],

            "start" => substr($r["start_time"], 0, 5),
            "start_time" => substr($r["start_time"], 0, 5),

            "end" => substr($r["end_time"], 0, 5),
            "end_time" => substr($r["end_time"], 0, 5),

            "wage" => (int)$r["wage"],
            "kids" => (int)$r["kids"],
            "ages" => $r["ages"],

            "phone" => $r["phone"],
            "urgent" => (int)$r["urgent"],

            "type" => $r["shift_type"],
            "shift_type" => $r["shift_type"],

            "requirements" => $r["notes"],
            "notes" => $r["notes"],

            "created_at" => $r["created_at"]
        ];
    }

    $json = json_encode($rows, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

    $content =
        "/* auto-generated by post_shift.php - do not edit manually */\n" .
        "window.SHIFTS = " . $json . ";\n";

    $path = __DIR__ . "/shifts_data.js";
    if (file_put_contents($path, $content) === false) {
        die("Failed to write shifts_data.js. Check permissions (664/666).");
    }
}

if ($_SERVER["REQUEST_METHOD"] !== "POST") {
    die_bad("Method not allowed");
}

$k_name     = trim($_POST["k_name"] ?? "");
$city       = trim($_POST["city"] ?? "");
$address    = trim($_POST["address"] ?? "");
$shift_type = trim($_POST["shift_type"] ?? "גן");
$ages       = trim($_POST["ages"] ?? "");

$shift_date = trim($_POST["shift_date"] ?? "");
$start_time = trim($_POST["start_time"] ?? "");
$end_time   = trim($_POST["end_time"] ?? "");

$wage = isset($_POST["wage"]) ? (int)$_POST["wage"] : 0;
$kids = isset($_POST["kids"]) ? (int)$_POST["kids"] : 0;

$phone  = trim($_POST["phone"] ?? "");
$notes  = trim($_POST["notes"] ?? "");
$urgent = isset($_POST["urgent"]) ? 1 : 0;

if ($k_name==="" || $city==="" || $address==="" || $shift_date==="" || $start_time==="" || $end_time==="" || $phone==="") {
    die_bad("Missing required fields.");
}

// מאפשר משמרת לילה (חוצה חצות), רק מונע זהות
if ($start_time === $end_time) {
    die_bad("Invalid time range.");
}

$sql = "INSERT INTO shifts
        (k_name, city, address, shift_date, start_time, end_time, wage, kids, ages, phone, urgent, shift_type, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = $conn->prepare($sql);
if ($stmt === false) {
    die("Prepare failed: " . $conn->error);
}

$stmt->bind_param(
    "ssssssiississ",
    $k_name, $city, $address, $shift_date, $start_time, $end_time,
    $wage, $kids, $ages, $phone, $urgent, $shift_type, $notes
);

if ($stmt->execute() === false) {
    die("Insert failed: " . $stmt->error);
}

$stmt->close();

// בלי AJAX: מייצר מחדש את shifts_data.js מה-DB
regenerate_shifts_js($conn);

$conn->close();

header("Location: post_shift.html?success=1");
exit;
?>
