<?php
$host = "localhost";
$port = 3306;
$db   = "roiwi_ex3";
$user = "roiwi_roiwi";
$pass = "roiwi_roiwi";

$conn = new mysqli($host, $user, $pass, $db, $port);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
$conn->set_charset("utf8mb4");

/* טבלה לפרסום משמרות */
$conn->query("CREATE TABLE IF NOT EXISTS shifts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  k_name VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  shift_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  wage INT NOT NULL,
  kids INT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  urgent TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

/* פונקציות עזר */
function die_bad($msg) { http_response_code(400); die($msg); }

function compute_hours_label($start, $end) {
  if ($start <= "09:00" && $end >= "15:00") return "מלא";
  if ($start < "12:00") return "בוקר";
  return "צהריים";
}

function compute_type_from_title($title) {
  return (mb_strpos($title, "משפחתון") !== false) ? "משפחתון" : "גן";
}

/* חייבים POST */
if ($_SERVER["REQUEST_METHOD"] !== "POST") {
  die_bad("Method not allowed");
}

/* קליטת נתונים */
$k_name     = trim($_POST['k_name'] ?? '');
$city       = trim($_POST['city'] ?? '');
$shift_date = trim($_POST['shift_date'] ?? '');
$start_time = trim($_POST['start_time'] ?? '');
$end_time   = trim($_POST['end_time'] ?? '');
$wage       = trim($_POST['wage'] ?? '');
$kids       = trim($_POST['kids'] ?? '');
$phone      = trim($_POST['phone'] ?? '');
$notes      = trim($_POST['notes'] ?? '');
$urgent     = isset($_POST['urgent']) ? 1 : 0;

/* ולידציות שרת */
if ($k_name==='' || $city==='' || $shift_date==='' || $start_time==='' || $end_time==='' ||
    $wage==='' || $kids==='' || $phone==='') {
  die_bad("Missing required fields.");
}
$wage_i = (int)$wage;
$kids_i = (int)$kids;

if ($wage_i < 30 || $wage_i > 100) die_bad("Invalid wage.");
if ($kids_i < 1 || $kids_i > 60) die_bad("Invalid kids.");
if (!preg_match('/^05\d-?\d{7}$/', $phone)) die_bad("Invalid phone.");
if ($end_time <= $start_time) die_bad("Invalid time range.");

$today = date("Y-m-d");
if ($shift_date < $today) die_bad("Invalid date.");

/* INSERT */
$sql = "INSERT INTO shifts
        (k_name, city, shift_date, start_time, end_time, wage, kids, phone, urgent, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

$stmt = $conn->prepare($sql);
if ($stmt === false) die_bad("Prepare failed: " . $conn->error);

$stmt->bind_param(
  "sssssiiiss",
  $k_name, $city, $shift_date, $start_time, $end_time, $wage_i, $kids_i, $phone, $urgent, $notes
);

if ($stmt->execute() === false) {
  $stmt->close();
  die_bad("Insert failed: " . $stmt->error);
}
$stmt->close();

/* ייצור/עדכון קובץ סטטי shifts_data.js */
$res = $conn->query("SELECT * FROM shifts ORDER BY id DESC");
if (!$res) die_bad("Select failed: " . $conn->error);

$rows = [];
while ($r = $res->fetch_assoc()) {
  $title = $r['k_name'];
  $hours = compute_hours_label(substr($r['start_time'],0,5), substr($r['end_time'],0,5));
  $type  = compute_type_from_title($title);

  $rows[] = [
    "id" => (int)$r["id"],
    "title" => $title,
    "city" => $r["city"],
    "area" => "",
    "address" => "",
    "date" => $r["shift_date"],
    "start" => substr($r["start_time"], 0, 5),
    "end" => substr($r["end_time"], 0, 5),
    "wage" => (int)$r["wage"],
    "type" => $type,
    "hours" => $hours,
    "urgent" => ((int)$r["urgent"] === 1),
    "ages" => "",
    "requirements" => $r["notes"] ?? "",
    "kids" => (int)$r["kids"],
    "phone" => $r["phone"]
  ];
}

$conn->close();

$js = "/* auto-generated by post_shift.php - do not edit manually */\n";
$js .= "window.SHIFTS = " . json_encode($rows, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . ";\n";

@file_put_contents(__DIR__ . "/shifts_data.js", $js, LOCK_EX);

/* חזרה לחיפוש */
header("Location: ShiftSearch.html?posted=1");
exit;
?>
