<?php
/* ================================
   קובץ: post_shift.php
   תפקיד: קבלת טופס יצירת משמרת,
           שמירה ל-DB,
           יצירת shifts_data.js מחדש,
           והפניה חזרה לדף
================================ */

/* פרטי חיבור למסד הנתונים */
$host = "localhost";        // שרת מסד הנתונים
$port = 3306;               // פורט ברירת מחדל של MySQL
$db   = "roiwi_ex3";        // שם בסיס הנתונים
$user = "roiwi_roiwi";      // שם משתמש ל-DB
$pass = "roiwi_roiwi";      // סיסמה ל-DB

/* יצירת חיבור ל-MySQL */
$conn = new mysqli($host, $user, $pass, $db, $port);

/* בדיקה אם החיבור נכשל */
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

/* הגדרת קידוד UTF-8 מלא (תמיכה בעברית ואימוג’ים וכו') */
$conn->set_charset("utf8mb4");

/* פונקציה אחידה להחזרת שגיאת 400 (Bad Request) */
function die_bad($msg) {
    http_response_code(400); // סטטוס HTTP 400
    die($msg);               // עצירת הסקריפט עם הודעה
}

/* ===========================================
   פונקציה: regenerate_shifts_js
   תפקיד:
   שולפת את כל המשמרות מה-DB
   ומייצרת מחדש קובץ JS עם הנתונים
=========================================== */
function regenerate_shifts_js($conn) {

    /* שאילתה לשליפת כל המשמרות,
       ממוינות לפי תאריך יצירה (מהחדש לישן) */
    $sql = "SELECT id, k_name, city, address, shift_date, start_time, end_time,
                   wage, kids, ages, phone, urgent, shift_type, notes, created_at
            FROM shifts
            ORDER BY created_at DESC";

    $res = $conn->query($sql);

    /* בדיקה אם השאילתה נכשלה */
    if (!$res) die("Select failed: " . $conn->error);

    $rows = [];

    /* מעבר על כל רשומה והכנסה למערך */
    while ($r = $res->fetch_assoc()) {

        /* בניית אובייקט מוכן ל-JS */
        $rows[] = [

            /* המרה ל-int עבור שדות מספריים */
            "id" => (int)$r["id"],

            /* כפילות שדות לטובת תאימות לקוד JS */
            "title" => $r["k_name"],
            "k_name" => $r["k_name"],

            "city" => $r["city"],
            "address" => $r["address"],

            "date" => $r["shift_date"],
            "shift_date" => $r["shift_date"],

            /* חיתוך השעה לפורמט HH:MM */
            "start" => substr($r["start_time"], 0, 5),
            "start_time" => substr($r["start_time"], 0, 5),

            "end" => substr($r["end_time"], 0, 5),
            "end_time" => substr($r["end_time"], 0, 5),

            "wage" => (int)$r["wage"],
            "kids" => (int)$r["kids"],
            "ages" => $r["ages"],

            "phone" => $r["phone"],

            /* המרה ל-0/1 */
            "urgent" => (int)$r["urgent"],

            "type" => $r["shift_type"],
            "shift_type" => $r["shift_type"],

            /* כפילות לשימושים שונים בצד לקוח */
            "requirements" => $r["notes"],
            "notes" => $r["notes"],

            "created_at" => $r["created_at"]
        ];
    }

    /* המרת המערך ל-JSON */
    $json = json_encode($rows, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

    /* יצירת תוכן קובץ JS */
    $content =
        "/* auto-generated by post_shift.php - do not edit manually */\n" .
        "window.SHIFTS = " . $json . ";\n";

    /* נתיב לקובץ shifts_data.js באותה תיקייה */
    $path = __DIR__ . "/GanSitter/shifts_data.js";

    /* כתיבת הקובץ מחדש */
    if (file_put_contents($path, $content) === false) {
        die("Failed to write shifts_data.js. Check permissions (664/666).");
    }
}

/* ===============================
   בדיקה שהבקשה היא POST בלבד
=============================== */
if ($_SERVER["REQUEST_METHOD"] !== "POST") {
    die_bad("Method not allowed");
}

/* ===============================
   קליטת נתונים מהטופס (POST)
   + ניקוי רווחים מיותרים
=============================== */
$k_name     = trim($_POST["k_name"] ?? "");
$city       = trim($_POST["city"] ?? "");
$address    = trim($_POST["address"] ?? "");
$shift_type = trim($_POST["shift_type"] ?? "גן");
$ages       = trim($_POST["ages"] ?? "");

$shift_date = trim($_POST["shift_date"] ?? "");
$start_time = trim($_POST["start_time"] ?? "");
$end_time   = trim($_POST["end_time"] ?? "");

/* המרה לשדות מספריים */
$wage = isset($_POST["wage"]) ? (int)$_POST["wage"] : 0;
$kids = isset($_POST["kids"]) ? (int)$_POST["kids"] : 0;

$phone  = trim($_POST["phone"] ?? "");
$notes  = trim($_POST["notes"] ?? "");
$urgent = isset($_POST["urgent"]) ? 1 : 0; // אם סומן צ’קבוקס

/* ===============================
   ולידציה בסיסית לשדות חובה
=============================== */
if ($k_name==="" || $city==="" || $address==="" || 
    $shift_date==="" || $start_time==="" || 
    $end_time==="" || $phone==="") {
    die_bad("Missing required fields.");
}

/* מאפשר משמרת לילה (חוצה חצות)
   רק מונע מצב שבו שעות זהות */
if ($start_time === $end_time) {
    die_bad("Invalid time range.");
}

/* ===============================
   הכנת שאילתת INSERT מאובטחת
   (Prepared Statement)
=============================== */
$sql = "INSERT INTO shifts
        (k_name, city, address, shift_date, start_time, end_time, wage, kids, ages, phone, urgent, shift_type, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

/* הכנת השאילתה */
$stmt = $conn->prepare($sql);
if ($stmt === false) {
    die("Prepare failed: " . $conn->error);
}

/* קישור פרמטרים:
   s = string
   i = integer */
$stmt->bind_param(
    "ssssssiississ",
    $k_name, $city, $address, $shift_date, $start_time, $end_time,
    $wage, $kids, $ages, $phone, $urgent, $shift_type, $notes
);

/* ביצוע השאילתה */
if ($stmt->execute() === false) {
    die("Insert failed: " . $stmt->error);
}

/* סגירת ה-statement */
$stmt->close();

/* ==================================
   בלי AJAX:
   מייצר מחדש shifts_data.js
   אחרי כל הוספה למסד
================================== */
regenerate_shifts_js($conn);

/* סגירת חיבור למסד */
$conn->close();

/* הפניה חזרה לדף הטופס עם אינדיקציה להצלחה */
header("Location: post_shift.html?success=1");
exit;
?>

